channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - shapely
  - fiona
  - pyproj
  - pysal
  - geopandas
  - requests
  - folium
  - seaborn
  - scikit-learn
  - scikit-image
  - gdal
  - rasterio
  - pip:
    - opencv-python
    - pygeoprocessing
